# Generated by Django 2.2 on 2019-05-01 10:50

from django.db import migrations, models
import explorer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default=explorer.models.generate_random_hex, max_length=64)),
                ('data', models.TextField()),
                ('signature', models.TextField(default=explorer.models.generate_random_base64)),
                ('insuranceHasPermission', models.BooleanField(default=False)),
                ('createdBy', models.CharField(max_length=400)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('type', models.TextField()),
            ],
        ),
    ]
